export const categories = [
    {
        title: "Filmes:",
        items: [
            {
                nome: "Transformers",
                resolucao: "HD",
                img: "https://sm.ign.com/t/ign_in/image/h/how-to-wat/how-to-watch-the-transformers-movies-in-chronological-order_f2k7.960.jpg",
                top10: true,
                badge: "Clássico",
                badgeColor: "red",
                progress: 0,
                youtube: "https://www.youtube.com/watch?v=CbX_SIz_9fk",
                generos: ["Ação", "Ficção Científica", "Aventura"],
                breveDescricao:"Transformers narra a guerra intergaláctica entre os Autobots, que buscam proteger a Terra, e os Decepticons, liderados por Megatron, que tentam dominar o planeta em busca do Allspark, um artefato capaz de dar vida a máquinas.",
            },
            {
                nome: "Duna",
                resolucao: "UHD",
                img: "https://cdn.europosters.eu/image/hp/116547.jpg",
                progress: 0,
                youtube: "https://www.youtube.com/watch?v=n9xhJrPXop4",
                generos: ["Fantasia", "Aventura", "Família"],
                breveDescricao:"História que se passa em um futuro feudal intergalático onde planetas são governados por grandes casas nobres.",
            },
            {
                nome: "Superman",
                resolucao: "HD",
                img: "https://editorial.rottentomatoes.com/wp-content/uploads/2024/05/EWKA_Superman_Poster.jpg",
                progress: 0,
                youtube: "https://www.youtube.com/watch?v=14qzQDMcTqM",
                generos: ["Ação", "Aventura", "Ficção Científica"],
                breveDescricao:"Um jovem repórter que luta para conciliar sua herança kryptoniana com sua criação humana no Kansas, três anos após assumir publicamente sua identidade como herói.",
            },
            {
                nome: "Vingadores",
                resolucao: "4K",
                img: "https://wallpaperbat.com/img/394281-best-avengers-wallpaper-for-desktop-avengers.jpg",
                progress: 0,
                youtube: "https://www.youtube.com/watch?v=KeNEGtsCWEk",
                generos: ["Ação", "Aventura", "Super-herói"],
                breveDescricao:"Um grupo de super-heróis conhecido mundialmente como Vingadores se une para derrotar uma calamidade que ameaça extinguir a humanidade.",
            },
            {
                nome: "Gladiador",
                resolucao: "HD",
                img: "https://aventurasnahistoria.com.br/wp-content/uploads/entretenimento/gladiador_2_VvnGVes.jpg",
                progress: 0,
                youtube: "https://www.youtube.com/watch?v=P5ieIbInFpg",
                generos: ["Ação", "Drama", "Histórico"],
                breveDescricao:"Filme que narra a história de Maximus Decimus Meridius, um general romano leal que, após liderar o exército à vitória contra as tribos germânicas, deseja apenas retornar à sua família.",
            },
            {
                nome: "Avatar",
                resolucao: "4K",
                img: "https://imgs.search.brave.com/Bqe5HFQa46D7XX5ZWJZhE3aSh1F5HYOrD9nGB6LWYSI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZS50bWRiLm9yZy90/L3AvdzUwMC82QWYz/SXFzcDY2dXRjTkhY/anZDRTJqN0pYenIu/anBn",
                progress: 0,
                youtube: "https://www.youtube.com/watch?v=5PSNL1qE6VY",
                generos: ["Aventura", "Fantasia", "Ficção Científica"],
                breveDescricao:"História de Jake Sully, um ex-fuzileiro naval paraplégico que viaja ao planeta Pandora para substituir seu irmão gêmeo no Programa Avatar.",
            },
        ],
    },
    {
        title: "Séries:",
        items: [
            {
                nome: "The Boys",
                resolucao: "UHD",
                img: "https://comicbookmovie.com/cdn-cgi/image/fit=cover,width=920,quality=75/images/articles/banners/the-boys-members-of-the-seven-suit-up-in-first-official-season-5-set-photo-ab214874.jpg",
                top10: true,
                badge: "Nova temporada",
                badgeColor: "red",
                youtube: "https://www.youtube.com/watch?v=tcrNsIaQkb4",
                generos: ["Ação", "Comédia", "Super-herói"],
                breveDescricao:"Traumatizado e desiludido com a corrupção dos heróis, Hughie é recrutado por Billy Butcher para se juntar a um grupo de vigilantes chamado The Boys.",
            },
            {
                nome: "Invencível",
                resolucao: "HD",
                img: "https://cloud.estacaonerd.com/wp-content/uploads/2021/04/28112011/Invencivel-01.jpg",
                top10: true,
                youtube: "https://www.youtube.com/watch?v=QvnTluSzq8s",
                generos: ["Animação", "Ação", "Super-herói"],
                breveDescricao:"Acompanha a história de Mark Grayson, um adolescente de 17 anos que finalmente herda superpoderes do seu pai, Omni-Man.",
            },
            {
                nome: "Os Anéis de Poder",
                resolucao: "UHD",
                img: "https://wallpapercave.com/wp/wp11097621.jpg",
                badge: "Novo episódio",
                badgeColor: "red",
                youtube: "https://www.youtube.com/watch?v=v7v1hIkYH24",
                generos: ["Drama", "Mistério", "Ficção Científica"],
                breveDescricao:"História ambientada na Segunda Era da Terra Média, milhares de anos antes dos eventos de O Senhor dos Anéis.",
            },
            {
                nome: "Jujutsu Kaisen",
                resolucao: "HD",
                img: "https://images5.alphacoders.com/126/thumbbig-1262882.webp",
                badge: "Novidade",
                badgeColor: "red",
                youtube: "https://www.youtube.com/watch?v=RYI-WG_HFV8",
                generos: ["Ação", "Aventura", "Fantasia"],
                breveDescricao:"Jujutsu Kaisen acompanha Yuji Itadori, um adolescente com força física excepcional que, após a morte de seu avô, se junta à escola Jujutsu.",
            },
            {
                nome: "Monarch: Legado dos Monstros",
                resolucao: "UHD",
                img: "https://godzilla.com/cdn/shop/articles/Monarch_101_F00494F.jpg?v=1774295665",
                badge: "Novidade",
                badgeColor: "red",
                youtube: "https://www.youtube.com/watch?v=JLHsM4bpfxY",
                generos: ["Ação", "Ficção Científica", "Monstros"],
                breveDescricao:"Monarch: Legado de Monstros acompanha a história da família Randa após a batalha entre Godzilla e os Titãs em São Francisco.",
            },
            {
                nome: "Cyberpunk: Edgerunners",
                resolucao: "4K",
                img: "https://wallpaperbat.com/img/1695668-cyberpunk-edgerunners-3840x2160-r-wallpaper.png",
                badge: "Novidade",
                badgeColor: "red",
                youtube: "https://www.youtube.com/watch?v=JtqIas3bYhg",
                generos: ["Animação", "Ação", "Ficção Científica"],
                breveDescricao:"A história acompanha David Martinez, um jovem talentoso e impulsivo que, após perder tudo em um tiroteio, decide sobreviver do lado errado da lei como um edgerunner.",
            },
        ],
    },
    {
        title: "Dicas de conteúdo baseado no seu gosto:",
        items: [
            {
                nome: "To Be Hero X",
                resolucao: "HD",
                img: "https://4kwallpapers.com/images/walls/thumbs_3t/22637.png",
                top10: true,
                youtube: "https://www.youtube.com/watch?v=WZdDIuejpgQ",
                generos: ["Ação", "Aventura", "Ficção Científica"],
                breveDescricao:"To Be Hero X é um anime chinês que se passa em um mundo onde o Valor de Confiança transforma pessoas em super-heróis.",
            },
            {
                nome: "One Punch Man",
                resolucao: "UHD",
                img: "https://wallpapers-clan.com/wp-content/uploads/2023/01/one-punch-man-saitama-pfp-5.jpg",
                top10: true,
                badge: "Novidade",
                badgeColor: "red",
                youtube: "https://www.youtube.com/watch?v=H23B_mh8sv4",
                generos: ["Animação", "Ação", "Comédia"],
                breveDescricao:"One Punch Man acompanha Saitama, um super-herói que se tornou tão poderoso após três anos de treinamento intenso que consegue derrotar qualquer inimigo com um único soco.",
            },
            {
                nome: "Breaking Bad",
                resolucao: "HD",
                img: "https://files.tecnoblog.net/wp-content/uploads/2022/06/breaking-bad.jpg",
                top10: true,
                badge: "Novo episódio",
                badgeColor: "red",
                youtube: "https://www.youtube.com/watch?v=_-Nv0JOcGxg",
                generos: ["Drama", "Crime", "Suspense"],
                breveDescricao:"Breaking Bad acompanha Walter White, um professor de química de meia-idade que após ser diagnosticado com câncer de pulmão terminal, ele decide usar seu conhecimento científico para produzir metanfetamina.",
            },
            {
                nome: "De Volta para o Futuro",
                resolucao: "HD",
                img: "https://imgs.search.brave.com/zFlNdNWTPU6i-SP-lP8ZYFZFx9gZGuWAgNhXQbH9ETo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL1Mv/cHYtdGFyZ2V0LWlt/YWdlcy85MDljZTNh/NWI3YzMwM2VjNDZl/MjIzOTk3M2JhZWY5/MzY5YzU4OTA3NWI0/M2FmMDU0MDAzYTZi/N2ZmOWNiMTQwLmpw/Zw",
                top10: true,
                badge: "Novo episódio",
                badgeColor: "red",
                youtube: "https://www.youtube.com/watch?v=qvsgGtivCgs",
                generos: ["Aventura", "Animação", "Família"],
                breveDescricao:"De Volta para o Futuro acompanha Marty McFly, um adolescente que, após uma experiência com o excêntrico cientista Dr. Emmett Brown , acaba viajando no tempo em um DeLorean modificado para 1955.",
            },
            {
                nome: "Dark",
                resolucao: "UHD",
                img: "https://kikacastro.com.br/wp-content/uploads/2020/08/dark.jpg",
                top10: true,
                badge: "Novo episódio",
                badgeColor: "red",
                youtube: "https://www.youtube.com/watch?v=JCCssUOtn2E",
                generos: ["Drama", "Mistério", "Ficção Científica"],
                breveDescricao:"Dark é uma série alemã de suspense e ficção científica que se passa na pequena cidade de Winden.",
            },
            {
                nome: "Rocky",
                resolucao: "4K",
                img: "https://imgs.search.brave.com/YAtcxM1Ohr4DptOc-VxDhl0lgJPkJKzWTKDI7vs8ChI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMuYW1jbmV0d29y/a3MuY29tL2FtY3R2/LmNvbS5ici93cC1j/b250ZW50L3VwbG9h/ZHMvMjAxOS8wMS9y/b2NreS5wbmc",
                top10: true,
                badge: "Novo episódio",
                badgeColor: "red",
                youtube: "https://www.youtube.com/watch?v=3VUblDwa648",
                generos: ["Drama", "Música", "Biografia"],
                breveDescricao:"Acompanha um boxeador amador de baixo escalão em Filadélfia, que trabalha como cobrador de dívidas para um agiota.",
            },
        ],
    },
];
